kind: Secret
apiVersion: v1
metadata:
  name: observatorium-configuration-red-hat-sso
  namespace: kafka-observability
stringData:
  tenant: <tenant>
  gateway: https://observatorium-mst.api.stage.openshift.com
  authType: redhat  
  redHatSsoAuthServerUrl: https://sso.redhat.com/auth/
  redHatSsoRealm: redhat-external
  metricsClientId: <metrics client id>
  metricsSecret: <metrics secret>   
  logsClientId: <logs client id>
  logsSecret: <logs secret>
type: Opaque